# Generated by Django 3.2.21 on 2023-10-05 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0147_alter_rounddatehistoryentry_reason"),
        ("polio", "0147_update_budget_processes"),
    ]

    operations = []
