# Generated by Django 3.2.21 on 2023-10-05 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0148_merge_20231005_0939"),
        ("polio", "0149_merge_20231005_1130"),
    ]

    operations = []
