# Generated by Django 3.2.21 on 2023-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0234_delete_reference_form_and_reference_instance"),
        ("polio", "0150_merge_20231005_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetprocess",
            name="teams",
            field=models.ManyToManyField(blank=True, null=True, related_name="budget_process_teams", to="iaso.Team"),
        ),
    ]
